### PR TITLE
Jackson 2.9.* QS updates remove model JSON output properties

### LINKED ISSUE #277: Jackson 2.9.* QS updates remove model JSON output properties
## Bug Report

**Current Behavior**
The output for the Core Components model JSON is erroneous for Jackson >= 2.9.0

This can be seen in the Navigation component where NavigationItem properties are present but the extended PageListItem properties are missing.

**Expected behavior/code**
The JSON output is as defined in existing unit tests following an update to Jackson 2.9.x

### PR DESCRIPTION
**Pull request by richardhand**
- updates jackson dependency version -> 2.9.5
- don’t filter out default method implementations

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #277 
| Patch: Bug Fix?          | 👍
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | Yes
| Documentation Provided   | N/A
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/jackson/DefaultMethodSkippingModuleProvider.java [hunk 1]
```diff
@@ -49,8 +51,15 @@ public DefaultMethodSkippingModuleProvider() {
                     if (member instanceof Method) {
                         final Method method = (Method) member;
                         if (method.isDefault()) {
-                            // only exclude default methods if they are defined on interfaces from the core components
-                            return !method.getDeclaringClass().getName().startsWith(PACKAGE_CORE_COMPONENTS);
+                            try {
+                                // only exclude default methods if they are defined on interfaces from the core components
+                                String className = beanDesc.getBeanClass().getMethod(method.getName()).getDeclaringClass().getName();
+                                return !className.startsWith(PACKAGE_CORE_COMPONENTS) ||
+                                    (className.startsWith(PACKAGE_CORE_COMPONENTS) &&
```
Comment (vladbailescu) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/jackson/DefaultMethodSkippingModuleProvider.java]: This is redundant:
- if `true`: `!true || (true && X) == X`
- if `false`: `!false || (false && X) == true`
Could be simplified to `!className.startsWith(PACKAGE_CORE_COMPONENTS) || className.contains(PACKAGE_IMPL_INTERNAL)`

Comment (richardhand) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/jackson/DefaultMethodSkippingModuleProvider.java]: updated in 5e845b93dd42bdb43be28085f632a5a58c33b334
