### PR TITLE
[Carousel/Tab] JS errors when using IE 11

### LINKED ISSUE #312: [Carousel/Tab] JS errors when using IE 11
When working with Carousel and Tabs on IE 11 the following Javascript errors/issues occur:

```
SCRIPT438: Object doesn't support property or method 'on'
clientlibs.js (148,21)
```

points to: [https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/development/content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/components/childreneditor/clientlibs/js/childreneditor.js#L148](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/development/content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/components/childreneditor/clientlibs/js/childreneditor.js#L148)

This means the 'Add' button does not work in the container dialogs.

----

```
SCRIPT438: Object doesn't support property or method 'closest'
clientlib-base.js (19271,17)
```

points to: [https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/development/content/src/content/jcr_root/apps/core/wcm/sandbox/components/tabs/v1/tabs/clientlibs/site/js/tabs.js#L102](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/development/content/src/content/jcr_root/apps/core/wcm/sandbox/components/tabs/v1/tabs/clientlibs/site/js/tabs.js#L102)

----

```
SCRIPT438: Object doesn't support property or method 'matches'
page.js (8455,17)
```

points to: [https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/development/content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/panelContainerUtils.js#L109](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/development/content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/panelContainerUtils.js#L109)

----

Also the panel list dropdown in the edit bar is not showing/flickering. Not sure if its a separate issue or due to above issues.

NOTE: IE11 is no longer supported for 6.5 and it looks like there are already page editor js errors piling up, e.g. drag'n'drop not working etc. Either use 6.4.1 or create the components in 6.5 in a different browser and reopen it in IE11.

(CQ-4254324)

### PR DESCRIPTION
**Pull request by richardhand**
* Ensures the add button (Coral) is ready before click binding
* Adds polyfills for matches and closest

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #312` 
| Patch: Bug Fix?          | 👍
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | N/A
| Documentation Provided   | N/A (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

File: content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelselect/js/polyfills.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
+/*******************************************************************************
```
Comment (vladbailescu) [inline content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelselect/js/polyfills.js]: Could we find a way to not duplicate the polyfills?

Comment (richardhand) [reply content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelselect/js/polyfills.js]: @vladbailescu - for the UI panel container / selector code, I moved to use the jQuery equivalents as we still widely use jQuery there.

For the tabs site clientlib, I added the polyfills directly, as we do for the image component. Again, we don't have a common component pattern which would be the ideal place for adding these polyfills so they could be used by all components. I think we can move them there when we create such a component.
