### PR TITLE
[Carousel] Navigation fails on a Carousel item selection from the Content Tree

### LINKED ISSUE #285: [Carousel] Navigation fails on a Carousel item selection from the Content Tree
## Bug Report

**Current Behavior**
When selecting a Carousel item from the Content Tree in the editor side panel, the corresponding component isn't navigated to / selected in the Carousel.

**Expected behavior/code**
Clicking an item in the Content Tree should navigate to the correct panel and ensure it's selected.

### PR DESCRIPTION
**Pull request by richardhand**
- introduces `cmp-panelcontainer-navigated` event.
- disables panel container item editable overlays that aren’t the active one.
- adds content tree listeners to navigate to and select panels on change.

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #285 
| Patch: Bug Fix?          | 👍
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | 
| Documentation Provided   |  (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

File: content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js [hunk 1]
```diff
@@ -164,6 +176,15 @@
...
             });
         }
+
+        /**
+         * Triggered when the Panel Container has navigated.
+         *
+         * @event CQ.CoreComponents.PanelContainer#cmp-panelcontainer-navigated
+         * @param {Object} event Event object.
+         * @param {String} event.id The Panel Container ID (path)
+         * @param {Number} event.index Index of the navigated to Panel Container item
```
Comment (jckautzmann) [inline content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js]: The description is a bit unclear. Maybe something like: 'Index of the Panel Container item that is navigated to'?

File: content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/contentTree.js [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+        contentTree: ".editor-ContentTree coral-tree"
+    };
+
+    /**
+     * Handling to ensure the {@link Granite.author.ui.ContentTree} selection logic functions
+     * with Panel Containers.
+     */
+
+    /**
+     * Sync Panel Container child {@link Granite.author.Editable} overlay disabled states on navigate,
```
Comment (jckautzmann) [inline content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/contentTree.js]: this sentence is not clear to me...

**Comment by richardhand** [comment]
@jckautzmann - addresses your feedback in https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/pull/286/commits/f4495217fca59274397e39a4c3270fc2de131529, is it a little clearer?

File: content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js [hunk 3]
```diff
@@ -20,6 +20,7 @@
     var GET_DATA_SUFFIX = ".model.json";
     var POST_SUFFIX = ".childreneditor.html";
     var MESSAGE_ID = "cmp.panelcontainer";
+    var NAVIGATE_DELAY = 200;
```
Comment (richardhand) [inline content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js]: @jckautzmann, @vladbailescu - this timeout is a little brittle, it's an approximation on the time to update/navigate the UI component after messaging the content frame. Without receiving a return message I don't see any other approach. Unless you have an idea?

File: content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js [hunk 4]
```diff
@@ -62,19 +63,30 @@
...
+
+                Granite.author.ContentFrame.postMessage(MESSAGE_ID, data);
+
+                setTimeout(function() {
+                    channel.trigger({
+                        type: "cmp-panelcontainer-navigated",
+                        id: data.id,
+                        index: data.index
+                    });
+                }, NAVIGATE_DELAY);
```
Comment (richardhand) [inline content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js]: @vladbailescu, @jckautzmann - this delay is a little brittle, it's an approximation on the time to update/navigate the UI component after posting the message to the content frame. Without receiving a return message I don't see a better approach unless you have an idea?

Comment (jckautzmann) [reply content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js]: @richardhand As you pointed, we could trigger a `navigationDone` event in the Carousel/Tabs js logic when the navigation is done and bind a handler here to listen to this event. I don't see other options.

File: content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js [hunk 5]
```diff
@@ -62,19 +63,30 @@
...
-                Granite.author.ContentFrame.postMessage(MESSAGE_ID, {
+                var data = {
                     id: this._config.path,
                     type: this._config.panelContainerType.name,
                     operation: "navigate",
                     index: index
-                });
+                };
+
+                Granite.author.ContentFrame.postMessage(MESSAGE_ID, data);
```
Comment (kwin) [inline content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js]: Granite.author is given via `ns`
