### PR TITLE
[Fixes #279] Edit action to open to the chosen variation of the content fragment

### LINKED ISSUE #279: Content fragment edit button always opens master variation
## Bug Report

**Current Behavior**
When clicking the edit button on the content fragment component users are always taken to the master variation in the content fragment editor instead of the specific variation referenced by the content fragment component.

**Expected behavior/code**
The content fragment editor should open on the specific variation selected.

**Environment**
- AEM version and patch level: 6.3.2.0
- Core Components version: 2.0.6, Core Components Extension version: 1.0.2
- JRE version: 1.8

**Possible Solution**

The javascript behind the edit button should be updated to add the variation as a query parameter.

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### PR DESCRIPTION
**Pull request by josephrignanese**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #279 
| Patch: Bug Fix?          | Bug Fix
| Minor: New Feature?      | Yes
| Major: Breaking Change?  | No
| Tests Added + Pass?      | No
| Documentation Provided   | No
| Any Dependency Changes?  | No
| License                  | Apache License, Version 2.0

Updated the edit action for content fragment components to open the selected content fragment variation by populating the `variation` query parameter with the `variationName` value for the CF Editor URL

### CODE REVIEW

**Comment by josephrignanese** [comment]
Hi @vladbailescu,
When do you think this might be merged and make it into a release?
Any feedback you'd like me to incorporate?

I was considering whether it is a good idea to use the Granite.author.CFM.Fragments.adaptToFragment function or if it is better to just get and parse the JSON without adding the dependency.

**Comment by vladbailescu** [comment]
@josephrignanese, is the `Granite.author.CFM.Fragments.adaptToFragment ` function available on all supported AEM versions (>= 6.3)? If yes, then I'd go with using it as an API instead of replicating the business logic into our components.

**Comment by richardhand** [comment]
This looks good to me, @vladbailescu - do you think we can merge here?

File: extension/contentfragment/content/src/content/jcr_root/apps/core/wcm/extension/components/contentfragment/v1/contentfragment/clientlibs/editor/authoring/js/editAction.js [hunk 1]
```diff
@@ -37,8 +37,13 @@
             // get the path of the content fragment
             var fragmentPath = $(editable.dom).find("." + CLASS_CONTENTFRAGMENT).attr(ATTRIBUTE_PATH);
             if (fragmentPath) {
+                var fragmentEditUrl = EDITOR_URL + fragmentPath;
+                var fragment = Granite.author.CFM.Fragments.adaptToFragment(editable.dom);
```
Comment (richardhand) [inline extension/contentfragment/content/src/content/jcr_root/apps/core/wcm/extension/components/contentfragment/v1/contentfragment/clientlibs/editor/authoring/js/editAction.js]: @josephrignanese - `Granite.author` is available in the closure as `ns` so we could use `ns.CFM.Fragments.adaptToFragment` just to be consistent with other usages.

**Comment by josephrignanese** [comment]
Thanks @richardhand, have updated to use ```ns``` and also addressed an issue that occurred when opening the editor with the master variation specified.
